apiVersion: aiedge.ndsl-lab.cn/v1
kind: Edge
metadata:
  name: aiedge-base-services
  # 对应Aiedge基础服务的配置，谨慎删改
spec:
  edgeName: "aiedge-base-services"
  imageRegistry: "registry.aiedge.ndsl-lab.cn"
  brokerClusterIp: "192.168.20.221"
  schedulerClusterIp: "192.168.20.221"
  # "rtmpServer": "rtmp://aiedge.ndsl-lab.cn:8035/live",
  # "httpServer": "http://aiedge.ndsl-lab.cn:8086/live"
---
apiVersion: aiedge.ndsl-lab.cn/v1
kind: Edge
metadata:
  name: edge1
spec:
  edgeName: "edge1"
  baseArch: "amd64"
  nodePortIp: "192.168.20.221"
  imageRegistry: "registry.aiedge.ndsl-lab.cn"
  nodes:
    - hostName: zqd-edge222
      gpuArch: None
---
apiVersion: aiedge.ndsl-lab.cn/v1
kind: Edge
metadata:
  name: edge2
spec:
  edgeName: "edge2"
  baseArch: "amd64"
  nodePortIp: "192.168.20.221"
  imageRegistry: "registry.aiedge.ndsl-lab.cn"
  nodes:
    - hostName: zqd-edge223
      gpuArch: None
