apiVersion: aiedge.ndsl-lab.cn/v1
kind: Edge
metadata:
  name: aiedge-base-services
  # 对应Aiedge基础服务的配置，谨慎删改
spec:
  edgeName: "aiedge-base-config"
  imageRegistry: "registry.aiedge.ndsl-lab.cn"
  brokerClusterIp: "192.168.20.151"
  schedulerClusterIp: "192.168.20.151"
---
apiVersion: aiedge.ndsl-lab.cn/v1
kind: Edge
metadata:
  name: edge1
spec:
  edgeName: "edge1"
  baseArch: "amd64"
  nodePortIp: "192.168.20.151"
  imageRegistry: "registry.aiedge.ndsl-lab.cn"
  nodes:
    - hostName: edge1-c153
      gpuArch: None 
    - hostName: edge1-c154
      gpuArch: None
    - hostName: edge1-nx248
      gpuArch: NX
    - hostName: edge1-nx168
      gpuArch: NX
    - hostName: edge1-nx90
      gpuArch: NX
    - hostName: edge1-nx40
      gpuArch: NX
---
apiVersion: aiedge.ndsl-lab.cn/v1
kind: Edge
metadata:
  name: edge2
spec:
  edgeName: "edge2"
  baseArch: "amd64"
  nodePortIp: "192.168.20.151"
  imageRegistry: "registry.aiedge.ndsl-lab.cn"
  nodes:
    - hostName: edge2-c156
      gpuArch: Geforce
