apiVersion: v1
kind: PersistentVolume
metadata:
  name: aiedge-mysql-pv
  namespace: aiedge
  labels:
    aiedge/component: ""
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/aiedge/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aiedge-mysql-pvc
  namespace: aiedge
  labels:
    aiedge/component: ""
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi